/home/user2/SOC/subip/AHB/ahb_matrix_1m2s.v
/home/user2/SOC/subip/AHB/ahb_to_apb_bridge_12.v
/home/user2/SOC/subip/clk_reset/soc_clk_rst_gen.v
/home/user2/SOC/subip/data_ram/mem_top.v
/home/user2/SOC/subip/debug_int/debug_apb_wrapper.v
/home/user2/SOC/subip/debug_int/debug_int.v
# /home/user2/SOC/subip/instruction_rom/instruction_memory.v
/home/user2/SOC/subip/src_gpio/gpio_apb_wrapper.v
/home/user2/SOC/subip/src_gpio/gpio.v
/home/user2/SOC/subip/timer_counter_imp/timer_apb_wrapper.v
/home/user2/SOC/subip/timer_counter_imp/timerr.v
/home/user2/SOC/subip/timer_counter_imp/timer.v
/home/user2/SOC/src/soc_integration.v
/home/user2/SOC/subip/RISC-V/alu.sv
/home/user2/SOC/subip/RISC-V/control_unit.sv
/home/user2/SOC/subip/RISC-V/cpu_top.sv
/home/user2/SOC/subip/RISC-V/data_ram.sv
/home/user2/SOC/subip/RISC-V/decoder.sv
/home/user2/SOC/subip/RISC-V/imm_gen.sv
/home/user2/SOC/subip/RISC-V/instr_rom.sv
/home/user2/SOC/subip/RISC-V/pc_reg.sv
/home/user2/SOC/subip/RISC-V/reg_file.sv
/home/user2/SOC/subip/spi/src/spi_apb_wrapper.sv
/home/user2/SOC/subip/spi/src/spi_master.sv
/home/user2/SOC/subip/UART/rtl/baud_gen.v
/home/user2/SOC/subip/UART/rtl/uart_regs.v
/home/user2/SOC/subip/UART/rtl/uart_rx.v
/home/user2/SOC/subip/UART/rtl/uart_top.v
/home/user2/SOC/subip/UART/rtl/uart_tx.v
/home/user2/SOC/subip/UART/rtl/uart_wrapper.v
/home/user2/SOC/subip/watchdog_timer/rtl/watchdog_apb_wrapper.v
/home/user2/SOC/subip/watchdog_timer/rtl/watch.v
/home/user2/SOC/subip/interrupt_controller/rtl/interruptcontroller_apb_wrapper.v
/home/user2/SOC/subip/interrupt_controller/rtl/interruptcontroller.v
